# Generated by Django 2.0.4 on 2018-07-16 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MXAsentamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_asentamiento', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Asentamiento',
                'verbose_name_plural': 'Asentamientos',
                'ordering': ('mx_municipio', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='MXCiudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ('mx_estado', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='MXEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('abbr', models.CharField(max_length=6, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='MXMunicipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clave', models.CharField(max_length=10)),
                ('mx_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='sepomex.MXEstado')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ('mx_estado', 'nombre'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='mxestado',
            unique_together={('nombre', 'abbr')},
        ),
        migrations.AddField(
            model_name='mxciudad',
            name='mx_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='sepomex.MXEstado'),
        ),
        migrations.AddField(
            model_name='mxasentamiento',
            name='mx_ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asentamientos', to='sepomex.MXCiudad'),
        ),
        migrations.AddField(
            model_name='mxasentamiento',
            name='mx_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asentamientos', to='sepomex.MXMunicipio'),
        ),
        migrations.AlterUniqueTogether(
            name='mxmunicipio',
            unique_together={('clave', 'nombre', 'mx_estado')},
        ),
    ]
