# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sepomex', '0007_auto_20170623_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mxasentamiento',
            options={'ordering': ('mx_municipio', 'nombre'), 'verbose_name': 'Asentamiento', 'verbose_name_plural': 'Asentamientos'},
        ),
        migrations.AlterModelOptions(
            name='mxciudad',
            options={'ordering': ('mx_estado', 'nombre'), 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='mxestado',
            options={'ordering': ('nombre',), 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='mxmunicipio',
            options={'ordering': ('mx_estado', 'nombre'), 'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
    ]
