# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sepomex', '0008_auto_20170906_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mxasentamiento',
            name='mx_ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asentamientos', to='sepomex.MXCiudad'),
        ),
        migrations.AlterField(
            model_name='mxasentamiento',
            name='mx_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asentamientos', to='sepomex.MXMunicipio'),
        ),
    ]
